name: Integration Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BACKEND_URL: "http://localhost:8080"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install

      - name: Build and start services
        run: docker compose up --build -d

      - name: Wait for Backend to be Ready
        run: |
          until nc -zv localhost 8080; do printf '.'; sleep 5; done

      - name: Run tests
        run: bun test --verbose --preload ./packages/integration-tests/setupTests.ts

      - name: Services teardown
        # even if the checks fail, we still want to teardown the container.
        if: always()
        run: docker compose down
