name: Integration Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run services
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml up --build -d

      - name: Run integration tests
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml up integration-test

      - name: Services teardown
        # even if the checks fail, we still want to teardown the container.
        if: always()
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml down
