name: Integration Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Run Services
        run: docker compose -f docker-compose.yml up --build -d

      - name: Run Integration Tests
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml run --rm integration-test

      - name: Services Teardown
        # even if the checks fail, we still want to teardown the container.
        if: always()
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml down
