name: Integration Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install

      - name: Build and start services
        run: docker compose up --build -d

      - name: Run tests
        run: bun test packages/integration-tests

      - name: Services teardown
        run: docker compose down
