name: Linting and formatting

permissions:
  contents: write

on:
  push:

jobs:
  lint-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install

      - name: Run eslint
        # If the actions don't fail that means linter passed
        run: bun run lint

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          author_name: Jonathan Koziel
          author_email: jonathankoziel1@gmail.com
          committer_name: Jonathan Koziel
          committer_email: jonathankoziel1@gmail.com

  format-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      - name: Format backend
        working-directory: ./backend/
        run: |
          go mod download
          go fmt ./...
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          author_name: Jonathan Koziel
          author_email: jonathankoziel1@gmail.com
          committer_name: Jonathan Koziel
          committer_email: jonathankoziel1@gmail.com
