name: Linting and formatting

on:
  push:

jobs:
  lint-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install

      - name: Run eslint
        # If the actions don't fail that means linter passed
        run: bun run lint
  format-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      - name: Format backend
        working-directory: ./backend/
        run: |
          go mod download
          go fmt .
